name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to display"
        required: true

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Triggered Workflow
        run: |
          echo "This is the triggered workflow!"
          echo 'This is the message: "${{ inputs.message }}"'
