name: Source Workflow

on:
  push:
    branches:
      - trigger

jobs:
  trigger-other:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/isahohieku/repo-trigger/actions/workflows/triggered-workflow.yml/dispatches \
            -d '{"ref":"main", "inputs":{"message":"Hello from the source workflow!"}}'
