name: Triggered Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run-automation

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Triggered Workflow
        run: echo "This is the triggered workflow!"
